- OpenSSL 0.9.8e throws errors like "./support/mkcert.sh: line 140: 18036 Illegal instruction $openssl genrsa -rand $randfiles -out $sslkeydir/ca.key 1024" during "make certificate TYPE=custom", therefore we use OpenSSL 0.9.7m now.
git-svn-id: svn://svn.ispconfig.org/ispconfig/branches/ISPConfig-2.2.stable@846 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/compile_aps/compile b/install_ispconfig/compile_aps/compile
--- a/install_ispconfig/compile_aps/compile
+++ b/install_ispconfig/compile_aps/compile
@@ -29,7 +29,7 @@
 
 PATH="/home/admispconfig/ispconfig/tools/clamav/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/libexec"
 
-OPENSSL=openssl-0.9.8e
+OPENSSL=openssl-0.9.7m
 APACHE=apache_1.3.39
 MOD_SSL=mod_ssl-2.8.30-1.3.39
 PHP=php-5.2.4
@@ -121,7 +121,7 @@ cd ../${MOD_SSL}
 cd ../${APACHE}
 make || error "Could not make Apache"
 if [ "$install_art" == "install" ]; then
-  make certificate TYPE=dummy || error "Could not make certificate for Apache"
+  make certificate TYPE=custom || error "Could not make certificate for Apache"
 fi
 make install || error "Could not install Apache"
 
