Added a second failsafe configure string in case that the first attempt to run configure for clamav fails.
git-svn-id: svn://svn.ispconfig.org/ispconfig/trunk@904 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/compile_aps/compile b/install_ispconfig/compile_aps/compile
--- a/install_ispconfig/compile_aps/compile
+++ b/install_ispconfig/compile_aps/compile
@@ -160,7 +160,10 @@ rm -fr ${INSTALL_ROOT_TMP}
 cd ${COMPILE_DIR}
 
 cd ${CLAMAV}
-./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav --sysconfdir=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc --with-user=adm${APPLICATION_NAME} --with-group=adm${APPLICATION_NAME} --disable-clamav --disable-bzip2 --disable-zlib-vcheck --disable-gcc-vcheck || error "Could not configure ClamAV"
+./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav --sysconfdir=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc --with-user=adm${APPLICATION_NAME} --with-group=adm${APPLICATION_NAME} --disable-clamav --disable-bzip2 --disable-zlib-vcheck
+if [ $? != 0 ]; then
+  ./configure --prefix=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav --sysconfdir=/home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/etc --with-user=adm${APPLICATION_NAME} --with-group=adm${APPLICATION_NAME} --disable-clamav --disable-bzip2 --disable-zlib-vcheck --disable-gcc-vcheck CFLAGS="-O0" || error "Could not configure ClamAV"
+fi
 make || error "Could not make ClamAV"
 make install || error "Could not install ClamAV"
 cp -f COPYING /home/adm${APPLICATION_NAME}/${APPLICATION_NAME}/tools/clamav/
