git-svn-id: svn://svn.ispconfig.org/ispconfig/branches/ISPConfig-2.2.stable@845 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/compile_aps/compile b/install_ispconfig/compile_aps/compile
--- a/install_ispconfig/compile_aps/compile
+++ b/install_ispconfig/compile_aps/compile
@@ -121,7 +121,7 @@ cd ../${MOD_SSL}
 cd ../${APACHE}
 make || error "Could not make Apache"
 if [ "$install_art" == "install" ]; then
-  make certificate TYPE=dummy  || error "Could not make certificate for Apache"
+  make certificate TYPE=dummy || error "Could not make certificate for Apache"
 fi
 make install || error "Could not install Apache"
 
