- The installer saves the old SSL certificate when ISPConfig is updated.
git-svn-id: svn://svn.ispconfig.org/ispconfig/branches/ISPConfig-2.2.stable@669 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/compile_aps/compile b/install_ispconfig/compile_aps/compile
--- a/install_ispconfig/compile_aps/compile
+++ b/install_ispconfig/compile_aps/compile
@@ -73,6 +73,12 @@ else
   WITH_ZLIB_DIR=""
 fi
 
+if [ "$install_art" == "upgrade" ]; then
+  SSL_CERTS="--with-key=/root/ispconfig/httpd/conf/ssl.key/server.key --with-crt=/root/ispconfig/httpd/conf/ssl.crt/server.crt"
+else
+  SSL_CERTS=""
+fi
+
 error ()
 {
   echo "ERROR: $1"
@@ -117,7 +123,7 @@ make || error "Could not make OpenSSL"
 make install || error "Could not install OpenSSL"
 
 cd ../${MOD_SSL}
-./configure --with-apache=../${APACHE} --with-ssl=${INSTALL_ROOT}/openssl --prefix=${INSTALL_ROOT}/httpd --enable-module=so || error "Could not configure Apache"
+./configure --with-apache=../${APACHE} --with-ssl=${INSTALL_ROOT}/openssl --prefix=${INSTALL_ROOT}/httpd --enable-module=so ${SSL_CERTS} || error "Could not configure Apache"
 cd ../${APACHE}
 make || error "Could not make Apache"
 make certificate TYPE=custom  || error "Could not make certificate for Apache"
