Added patches from stable version. In particular: - Custom templates can now be stored - Round Robin DNS now possible - /etc/Bastille/firewall.d/ will be kept during updates. - Added default SPF records. - Some bugfixes regarding default MX records. - The installer saves the old SSL certificate when ISPConfig is updated.
git-svn-id: svn://svn.ispconfig.org/ispconfig/trunk@714 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/compile_aps/compile b/install_ispconfig/compile_aps/compile
--- a/install_ispconfig/compile_aps/compile
+++ b/install_ispconfig/compile_aps/compile
@@ -123,7 +123,9 @@ cd ../${MOD_SSL}
 ./configure --with-apache=../${APACHE} --with-ssl=${INSTALL_ROOT}/openssl --prefix=${INSTALL_ROOT}/httpd --enable-module=so || error "Could not configure Apache"
 cd ../${APACHE}
 make || error "Could not make Apache"
-make certificate TYPE=custom  || error "Could not make certificate for Apache"
+if [ "$install_art" == "install" ]; then
+  make certificate TYPE=custom  || error "Could not make certificate for Apache"
+fi
 make install || error "Could not install Apache"
 
 cd ../${PHP}
