- Added g++ check to the installer. - Modified rc_edit() function to make daemons start/stop on SuSE systems.
git-svn-id: svn://svn.ispconfig.org/ispconfig/branches/ISPConfig-2.2.stable@430 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/setup2 b/install_ispconfig/setup2
--- a/install_ispconfig/setup2
+++ b/install_ispconfig/setup2
@@ -737,6 +737,17 @@ fi  ## install_art == install
   fi
 
   echo
+  echo "########## g++ ##########"
+  echo
+  which g++
+  if [ $? != 0 ]; then
+    error "g++ not found!";
+  else
+    log "g++ found: `which g++`"
+    echo OK
+  fi
+
+  echo
   echo "########## INSTALLATION ##########"
   echo
   if [ -f /etc/my.cnf ]; then
