Added a check for xml2-dev in the the setup script.
git-svn-id: svn://svn.ispconfig.org/ispconfig/trunk@612 418fc7b0-dcfb-0310-bdb1-f3812d3f35a6

diff --git a/install_ispconfig/setup2 b/install_ispconfig/setup2
--- a/install_ispconfig/setup2
+++ b/install_ispconfig/setup2
@@ -831,6 +831,17 @@ fi  ## install_art == install
     log "g++ found: `which g++`"
     echo OK
   fi
+  
+  echo
+  echo "########## xml2-dev ##########"
+  echo
+  which xml2-config
+  if [ $? != 0 ]; then
+    error "xml2-dev (xml2-config) not found!";
+  else
+    log "xml2-dev found: `which xml2-config`"
+    echo OK
+  fi
 
   echo
   echo "########## INSTALLATION ##########"
